version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-default@default.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - ${PGADMIN_PORT:-5050}:80
    restart: unless-stopped

  # server:
  #   container_name: gis_server
  #   build: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - ${SERVER_PORT:-5000}:3000
  #   depends_on:
  #     - pgadmin
  #   env_file:
  #     - .env
  #   restart: unless-stopped
