version: '3.9'

services:
    db:
        container_name: pg_db
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: root
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
        volumes:
            - ./volumes/postgres_data:/var/lib/postgresql/data

        ports:
            - 5432:5432
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - ${PGADMIN_PORT:-5050}:80
        restart: unless-stopped